### ISSUE TITLE
Reacsting error - UDS corpus

### ISSUE THREAD

**Issue by tommasoc80** [sidsvash26/temporal_nli#3]
Hi, 
I am trying to extract the training examples for fine-tuning the language models. When I process the UDST dataset I get the following error:

Traceback (most recent call last):
  File "recast_temporal_duration_rte.py", line 25, in <module>
    import doc_utils
  File "/temporal_nli/src/recasting/doc_utils.py", line 4, in <module>
    import decomp
  File "/temporal_nli/src/recasting/decomp/decomp/__init__.py", line 11, in <module>
    from .semantics.uds import UDSCorpus
  File "/temporal_nli/src/recasting/decomp/decomp/semantics/uds/__init__.py", line 3, in <module>
    from .corpus import UDSCorpus
  File "/temporal_nli/src/recasting/decomp/decomp/semantics/uds/corpus.py", line 24, in <module>
    from rdflib.plugins.sparql.sparql import Query
  File "/virtualenvs/temporal_nli-f6VPCCwd/lib/python3.8/site-packages/rdflib-4.2.2-py3.8.egg/rdflib/plugins/sparql/__init__.py", line 35, in <module>
    from . import parser
  File "/virtualenvs/temporal_nli-f6VPCCwd/lib/python3.8/site-packages/rdflib-4.2.2-py3.8.egg/rdflib/plugins/sparql/parser.py", line 182, in <module>
    Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()
  File "/.local/share/virtualenvs/temporal_nli-f6VPCCwd/lib/python3.8/site-packages/rdflib-4.2.2-py3.8.egg/rdflib/plugins/sparql/parserutils.py", line 113, in __init__
    self.name = name
AttributeError: can't set attribute

Any suggestion?

**Comment by sidsvash26** [comment]
@tommasoc80 This looks like an issue with the installation of the decomp package.

Can you check in your environment, if this works without any errors for you:

```python

import decomp
decomp_graph = decomp.UDSCorpus()
decomp_graph["ewt-train-1"].semantics_edges()
```

If this doesn't work, try reinstalling decomp package inside your environment -- https://github.com/decompositional-semantics-initiative/decomp

If the above works fine, the problem is something else. In that case, could you please let me know in what order you are running the scripts and which script is causing you the problem (along with the executed command).

**Comment by sidsvash26** [comment]
Closing issue due to inactivity. Please re-open if your issue is still not resolved.
